[theme]
inherit = basic
stylesheet = fuma.css, fuma-code.css
pygments_style = none

[options]
layout = docs
toc_style = normal
color_preset = neutral
search = true
fonts = bundled
sidebar_hide_name = false
default_open_level = 1
github_url =
edit_page_url_template =
nav_links =
sidebar_tabs =
announcement =
footer_text =
light_css_variables =
dark_css_variables =
