# Changes here will be overwritten by Copier
_commit: f9bac04
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: python-project-templates
project_description: Fumadocs theme for sphinx
project_name: sphinx-fuma
python_version_primary: '3.11'
team: the sphinx-fuma authors
